[project]
name = "gopolutils"
author = "Polshkrev"
description = "A collection of golang utilities."

[project.version]
major = 1
minor = 26
patch = 2

[license]
type = "MIT"
path = "LICENSE"

[urls]
repository = "https://github.com/Polshkrev/gopolutils"
reference = "https://pkg.go.dev/github.com/Polshkrev/gopolutils"
report = "https://goreportcard.com/report/github.com/Polshkrev/gopolutils"

[paths]
readme = "README.md"
todo = "TODO.md"

[commands]
test = ["go", "test", "-v", "./tests/..."]